### ISSUE TITLE
Hello, I have some question :)

### ISSUE THREAD

**Issue by XiaoliChan** [vayaconspade/ConvertTo-Json#5]
Can I merge your code into my future repository?

I create an information collector with PowerShell, and I use your ps1 to solved the [Convertto-json] function not found in Powershell 2.0 issues.

**Comment by EliteLoser** [comment]
Yes, it's open source. The MIT license allows it to be reused and distributed as parts of other works, etc. And I have no responsibility for errors or mishaps, etc. But if you find a bug, do report it so we can fix it if possible.

**Comment by XiaoliChan** [comment]
Thanks, I will write down your repository link at the beginning of my Readme file. : )

**Comment by EliteLoser** [comment]
Ok, thanks. Closing this issue. Good luck with your software.

**Comment by XiaoliChan** [comment]
Here is my repository: [Bloodhound.PS](https://github.com/XiaoliChan/Bloodhound.PS)

**Comment by EliteLoser** [comment]
Nice. Happy to help! (not my fault if bad guys use it... and the good guys can also use it...).
